#!/usr/bin/env node
/**
 * Embed a corporate mark into demo/theme.css as a data URI.
 *
 *   node scripts/embed-logo.mjs path/to/rochester-sensors.svg
 *   node scripts/embed-logo.mjs path/to/logo.png --width 190
 *   node scripts/embed-logo.mjs --clear
 *
 * The mark is INLINED, not linked. demo/standalone.html has to render from a
 * USB stick on a shop terminal with no network, and a test fails the build if
 * anything reaches out to a host. That rules out a CDN, and it also rules out
 * `<img src="logo.png">`, because the single-file build would have to carry the
 * file anyway.
 *
 * Prefer SVG. It inlines to a fraction of the size of a PNG at the same
 * fidelity, and it stays sharp on the 4K panel someone will inevitably mount on
 * a wall. A PNG works and is handled here, but budget for the bytes: base64
 * inflates by a third, and the standalone build carries the whole thing.
 *
 * Nothing else in the repository needs editing. This writes only into the
 * marked LOGO block of theme.css, so re-running it replaces the previous mark
 * rather than accumulating.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const themePath = join(root, 'demo', 'theme.css');

const MIME = {
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.gif': 'image/gif',
};

const START = '  /* --- LOGO: generated by scripts/embed-logo.mjs — do not hand-edit --- */';
const END = '  /* --- end LOGO --- */';

/** Intrinsic size, so the header reserves the right box instead of guessing. */
function measure(buffer, ext) {
  if (ext === '.svg') {
    const text = buffer.toString('utf8');
    const viewBox = text.match(/viewBox\s*=\s*["']\s*[\d.-]+[\s,]+[\d.-]+[\s,]+([\d.]+)[\s,]+([\d.]+)/i);
    if (viewBox) return { w: parseFloat(viewBox[1]), h: parseFloat(viewBox[2]) };
    const w = text.match(/\bwidth\s*=\s*["']([\d.]+)/i);
    const h = text.match(/\bheight\s*=\s*["']([\d.]+)/i);
    if (w && h) return { w: parseFloat(w[1]), h: parseFloat(h[1]) };
    return null;
  }
  if (ext === '.png' && buffer.length > 24 && buffer.toString('ascii', 12, 16) === 'IHDR') {
    return { w: buffer.readUInt32BE(16), h: buffer.readUInt32BE(20) };
  }
  return null;
}

function writeBlock(body) {
  const theme = readFileSync(themePath, 'utf8');
  const from = theme.indexOf(START);
  const to = theme.indexOf(END);
  if (from === -1 || to === -1) {
    throw new Error(`Could not find the LOGO block markers in ${themePath}`);
  }
  writeFileSync(themePath, theme.slice(0, from) + START + '\n' + body + theme.slice(to));
}

const args = process.argv.slice(2);

if (args.includes('--clear')) {
  writeBlock([
    '  --brand-logo: none;',
    '  --brand-logo-display: none;',
    '  --brand-logo-aspect: 3.5;',
    '  --brand-eyebrow-display: block;',
    '',
  ].join('\n'));
  console.log('Logo cleared — the header falls back to the text wordmark.');
  process.exit(0);
}

const [source] = args.filter((a) => !a.startsWith('--'));
if (!source) {
  console.error('Usage: node scripts/embed-logo.mjs <path-to-logo.svg|png> [--height 40]\n'
    + '       node scripts/embed-logo.mjs --clear');
  process.exit(1);
}

const heightFlag = args.indexOf('--height');
const height = heightFlag === -1 ? 40 : Number(args[heightFlag + 1]) || 40;

const ext = extname(source).toLowerCase();
const mime = MIME[ext];
if (!mime) {
  console.error(`Unsupported file type "${ext}". Use SVG (preferred), PNG, JPEG or WebP.`);
  process.exit(1);
}

const buffer = readFileSync(source);
const size = measure(buffer, ext);
const aspect = size ? +(size.w / size.h).toFixed(4) : 3.5;
const base64 = buffer.toString('base64');

writeBlock([
  `  --brand-logo: url("data:${mime};base64,${base64}");`,
  '  --brand-logo-display: block;',
  `  --brand-logo-height: ${height}px;`,
  `  --brand-logo-aspect: ${aspect};`,
  '  /* The text wordmark stands down once a real mark is present. */',
  '  --brand-eyebrow-display: none;',
  '',
].join('\n'));

const kb = Math.round(base64.length / 1024);
console.log(`Embedded ${source} (${mime}, ${kb} KB base64${size ? `, ${size.w}×${size.h}` : ''}).`);
if (kb > 120) {
  console.log('That is large for an inlined asset. An SVG of the same mark is usually under 10 KB,');
  console.log('and the standalone build carries every byte of this to the shop floor.');
}
console.log('\nNext:');
console.log('  node scripts/build-standalone.mjs');
console.log('  npm test');
