#!/usr/bin/env bash
#
# Installs a pre-push hook that runs the same checks CI would.
#
#     bash scripts/install-hooks.sh
#
# Opt-in on purpose: it adds roughly half a minute to every push, which is a
# fair trade when CI is running and a necessary one when it is not. Remove it
# with `rm .git/hooks/pre-push`, or skip it once with `git push --no-verify`.
set -euo pipefail

cd "$(dirname "$0")/.."
hook=".git/hooks/pre-push"

cat > "$hook" <<'HOOK'
#!/usr/bin/env bash
# Generated by scripts/install-hooks.sh — runs the checks CI would run.
set -uo pipefail
cd "$(git rev-parse --show-toplevel)"

fail() { echo ""; echo "  push blocked: $1"; echo "  fix it, or bypass once with: git push --no-verify"; exit 1; }

echo "pre-push: regenerating derived files…"
node scripts/build-demo-config.mjs >/dev/null || fail "the config generator errored"
node scripts/build-standalone.mjs  >/dev/null || fail "the standalone build errored"
git diff --quiet -- demo/data/downtime-reasons.js demo/standalone.html \
  || fail "generated files were stale — they have been rebuilt, review and commit them"

echo "pre-push: scanning for credentials and production addresses…"
bash scripts/scan-secrets.sh || fail "the secret scan found something"

echo "pre-push: running tests…"
npm test --silent || fail "tests failed"

echo "pre-push: all checks passed."
HOOK

chmod +x "$hook"
echo "Installed $hook"
echo "It regenerates derived files, scans for secrets and runs the test suite before every push."
